import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs';import os from 'node:os';import path from 'node:path'
import { openDatabase,migrate } from '../src/db.mjs'
import { candidateRow, drainOutbox, matchesCriterion, recoverBackgroundState, runMonitoringCycle, validateCandidate } from '../src/product.mjs'

function database(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'devsearch-product-')),db=openDatabase(path.join(dir,'db.sqlite'));migrate(db);t.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})});return db}
function seedUser(db,id='1'){db.prepare('INSERT INTO users(telegram_user_id,display_name) VALUES (?,?)').run(id,'Owner');return db.prepare('SELECT id FROM users WHERE telegram_user_id=?').get(id).id}

test('deterministic matcher applies query, skills, location and experience',()=>{const candidate={name:'Ali Karimov',headline:'Senior Node.js engineer',location:'Tashkent',experienceYears:6,skills:['Node.js','SQLite'],data:{}};assert.equal(matchesCriterion(candidate,{query:'senior node',filters:{location:'tashkent',minExperienceYears:5,skills:['node.js']}}),true);assert.equal(matchesCriterion(candidate,{query:'python',filters:{}}),false)})

test('candidate photo API shape survives migration and validates public URLs',t=>{const db=database(t);const columns=db.prepare('PRAGMA table_info(candidates)').all().map(x=>x.name);assert.ok(columns.includes('photo_url'));const photo={url:'https://cdn.example.test/alice.jpg',sourceUrl:'https://example.test/alice',method:'og:image'};assert.deepEqual(validateCandidate({name:'Alice',photo}).photo,photo);assert.throws(()=>validateCandidate({name:'Alice',photo:{...photo,url:'data:image/png,x'}}),/invalid photo URL/);db.prepare("INSERT INTO candidates(name,skills_json,contacts_json,photo_url,photo_source_url,photo_method,data_json,created_at,updated_at) VALUES ('Alice','[]','[]',?,?,?,'{}',1,1)").run(photo.url,photo.sourceUrl,photo.method);assert.deepEqual(candidateRow(db.prepare('SELECT * FROM candidates').get()).photo,photo)})

test('monitoring deduplicates matches and notification outbox',async t=>{const db=database(t),userId=seedUser(db),now=1000;db.prepare('INSERT INTO candidates(external_id,name,headline,location,experience_years,skills_json,contacts_json,data_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run('github:ali','Ali','Node developer','Tashkent',5,'["Node.js"]','[]','{}',now,now);const criterion=db.prepare('INSERT INTO saved_criteria(user_id,name,query,filters_json,enabled,interval_minutes,next_run_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(userId,'Node','node','{}',1,60,now,now,now);assert.equal(runMonitoringCycle(db,{now,criterionId:Number(criterion.lastInsertRowid),userId})[0].matchesFound,1);assert.equal(runMonitoringCycle(db,{now:now+1,criterionId:Number(criterion.lastInsertRowid),userId})[0].matchesFound,0);assert.equal(db.prepare('SELECT count(*) n FROM monitoring_matches').get().n,1);assert.equal(db.prepare('SELECT count(*) n FROM notification_outbox').get().n,1);const sent=[];assert.equal(await drainOutbox(db,async(id,payload)=>sent.push([id,payload.candidate.name]),{now}),1);assert.deepEqual(sent,[['1','Ali']]);assert.equal(db.prepare('SELECT status FROM notification_outbox').get().status,'sent')})

test('failed outbox deliveries are retryable with backoff',async t=>{const db=database(t),userId=seedUser(db),now=5000;db.exec(`INSERT INTO candidates(name,skills_json,contacts_json,data_json,created_at,updated_at) VALUES ('A','[]','[]','{}',${now},${now}); INSERT INTO saved_criteria(user_id,name,filters_json,created_at,updated_at) VALUES (${userId},'All','{}',${now},${now}); INSERT INTO monitoring_runs(criterion_id,started_at,status) VALUES (1,${now},'running'); INSERT INTO monitoring_matches(run_id,criterion_id,candidate_id,matched_at) VALUES (1,1,1,${now}); INSERT INTO notification_outbox(user_id,match_id,payload_json,available_at,created_at) VALUES (${userId},1,'{}',${now},${now})`);await drainOutbox(db,async()=>{throw new Error('offline')},{now});const row=db.prepare('SELECT status,attempts,available_at,last_error FROM notification_outbox').get();assert.equal(row.status,'failed');assert.equal(row.attempts,1);assert.ok(row.available_at>now);assert.equal(row.last_error,'offline')})
test('stale delivery leases and monitoring runs recover after restart',t=>{const db=database(t),userId=seedUser(db),now=1_000_000;db.exec(`INSERT INTO candidates(name,skills_json,contacts_json,data_json,created_at,updated_at) VALUES ('A','[]','[]','{}',1,1); INSERT INTO saved_criteria(user_id,name,filters_json,created_at,updated_at) VALUES (${userId},'All','{}',1,1); INSERT INTO monitoring_runs(criterion_id,started_at,status) VALUES (1,1,'running'); INSERT INTO monitoring_matches(run_id,criterion_id,candidate_id,matched_at) VALUES (1,1,1,1); INSERT INTO notification_outbox(user_id,match_id,payload_json,status,available_at,locked_at,created_at) VALUES (${userId},1,'{}','sending',1,1,1)`);recoverBackgroundState(db,{now,leaseMs:1000});assert.equal(db.prepare('SELECT status FROM monitoring_runs').get().status,'failed');const row=db.prepare('SELECT status,locked_at FROM notification_outbox').get();assert.equal(row.status,'failed');assert.equal(row.locked_at,null)})
