import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { crawlCandidates, discoverCandidateInputs, extractContacts, identifySource } from '../crawler.mjs'

const root=new URL('./fixtures/',import.meta.url)
const files={'fixture.test/':'index.html','fixture.test/about':'about.html','fixture.test/contact':'contact.html','portfolio.test/contact':'contact.html'}
function response(body,status=200,type='text/html'){return new Response(body,{status,headers:{'content-type':type}})}
const fetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response(u.hostname==='fixture.test'?'User-agent: *\nDisallow: /private\n':'User-agent: *\n');if(u.hostname==='github.com')return response('<a href="https://portfolio.test/contact">Portfolio website</a>');const f=files[`${u.hostname}${u.pathname}`];return f?response(await readFile(new URL(f,root),'utf8')):response('',404)}

test('deep traversal crosses profile to portfolio, extracts contacts and preserves provenance',async()=>{const r=await crawlCandidates([{id:'fixture',url:'https://fixture.test/'}],{fetch,delayMs:0,maxDepth:3,maxPages:12});const c=r.candidates[0];assert.ok(c);assert.equal(c.contacts.filter(x=>x.type==='email').length,1);assert.ok(c.contacts.some(x=>x.normalized==='+998901234567'));assert.ok(c.contacts.some(x=>x.type==='telegram'));assert.ok(c.contacts.some(x=>x.normalized==='linkedin:/in/fixture-dev'));assert.ok(!c.crawledPages.includes('https://fixture.test/private'));const linked=c.contacts.find(x=>x.normalized==='linkedin:/in/fixture-dev');assert.deepEqual(linked.discoveryChain,['https://fixture.test/','https://fixture.test/about','https://fixture.test/contact']);assert.ok(c.crawledPages.includes('https://portfolio.test/contact'))})

test('contact extraction handles mailto, tel and WhatsApp deterministically',()=>{const c=extractContacts('<a href="mailto:Dev@Example.uz?subject=Hi">mail</a><a href="tel:+998 90 111 22 33">call</a><a href="https://wa.me/998901112233">wa</a>','https://x.test/');assert.ok(c.some(x=>x.normalized==='dev@example.uz'));assert.equal(c.filter(x=>x.type==='phone'&&x.normalized.includes('998901112233')).length,2)})

test('deduplicates contacts and excludes candidates with no public contact',async()=>{const r=await crawlCandidates([{id:'none',url:'https://empty.test/'},{id:'fixture',url:'https://fixture.test/'}],{fetch:async(url,...args)=>new URL(url).hostname==='empty.test'?(new URL(url).pathname==='/robots.txt'?response(''):response('<p>Hello</p>')):fetch(url,...args),delayMs:0,maxDepth:2});assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].candidateId,'fixture');assert.equal(new Set(r.candidates[0].contacts.map(x=>`${x.type}:${x.normalized}`)).size,r.candidates[0].contacts.length);assert.equal(r.sourceReports.find(x=>x.candidateId==='none').status,'no-public-contact')})

test('source adapters identify priority sources and report restrictions',async()=>{assert.equal(identifySource('https://hh.uz/resume/1').id,'hh-uz');assert.equal(identifySource('https://olx.uz/d/obyavlenie/x').id,'olx-uz');assert.equal(identifySource('https://github.com/u').id,'github');const calls=[];const blocked=async url=>{calls.push(url);return new URL(url).pathname==='/robots.txt'?response('User-agent: *\n'):response('Access denied',403)};const r=await crawlCandidates([{id:'gh',url:'https://github.com/u'},{id:'hh',url:'https://hh.uz/resume/1'}],{fetch:blocked,delayMs:0});assert.ok(calls.findIndex(x=>x.includes('hh.uz/resume'))<calls.findIndex(x=>x.includes('github.com/u')));assert.equal(r.sourceReports.find(x=>x.candidateId==='hh').status,'access-blocked')})

test('robots exclusions are explicit rather than silently omitted',async()=>{const r=await crawlCandidates([{id:'private',url:'https://fixture.test/private'}],{fetch,delayMs:0});assert.equal(r.candidates.length,0);assert.equal(r.sourceReports[0].status,'robots-disallowed');assert.equal(r.sourceReports[0].failures[0].reason,'robots-disallowed')})

test('listing adapter discovers candidates across bounded pagination and starts provenance at listing',async()=>{const listingFetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('User-agent: *\n');if(u.pathname==='/search/resume'&&!u.search)return response('<a href="/resume/alice">Alice</a><a rel="next" href="?page=2">Next</a>');if(u.searchParams.get('page')==='2')return response('<a href="/resume/alice">duplicate</a><a href="/resume/bob">Bob</a><a rel="next" href="?page=3">Next</a>');if(u.searchParams.get('page')==='3')return response('<a href="/resume/ignored">Ignored</a>');if(u.pathname==='/resume/alice')return response('<p>Email alice@example.uz</p>');if(u.pathname==='/resume/bob')return response('<a href="https://t.me/bob_dev">Telegram</a>');return response('',404)};const r=await crawlCandidates([{id:'hh-list',type:'source',url:'https://hh.uz/search/resume'}],{fetch:listingFetch,delayMs:0,maxListingPages:2,maxDepth:0});assert.equal(r.discoveryReports[0].candidateCount,2);assert.equal(r.candidates.length,2);assert.deepEqual(r.candidates[0].contacts[0].discoveryChain.slice(0,2),['https://hh.uz/search/resume','https://hh.uz/resume/alice']);assert.ok(!r.candidates.some(x=>x.inputUrl.includes('ignored')))})

test('source adapters apply candidate-link rules without copying a channel name to every candidate',async()=>{const cases=[['https://olx.uz/rabota/','https://olx.uz/d/obyavlenie/frontend-ID1.html'],['https://it-market.uz/specialists','https://it-market.uz/specialist/42'],['https://t.me/s/resumes','https://t.me/s/resumes/123'],['https://github.com/search?q=uzbekistan&type=users','https://github.com/alice-dev'],['https://school.test/alumni','https://school.test/profile/alice']];for(const [listing,candidate] of cases){const d=await discoverCandidateInputs([{id:'s',type:'source',name:'Ustoz Shogird',url:listing}],{delayMs:0,maxListingPages:1,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response(`<a href="${candidate}">Candidate profile</a>`)});assert.equal(d.inputs[0]?.url,candidate,listing);assert.equal(d.inputs[0]?.name,undefined,listing);assert.equal(d.discoveryReports[0].status,'candidates-discovered')}})

test('unsupported and restricted listings are reported without fabricated candidates',async()=>{const unsupported=await discoverCandidateInputs([{id:'tp',type:'source',url:'https://talentpark.uz/search'},{id:'linkedin',type:'restricted',name:'LinkedIn',url:'https://linkedin.com/',reason:'login-required'},{id:'school',type:'unsupported',name:'School',url:'https://school.test/',reason:'no-adapter'}]);assert.equal(unsupported.inputs.length,0);assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='tp').status,'unsupported-source');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='linkedin').status,'restricted-source');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='linkedin').reason,'login-required');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='school').status,'unsupported-source');const restricted=await discoverCandidateInputs([{id:'gh',type:'source',url:'https://github.com/search?q=x&type=users'}],{delayMs:0,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response('blocked',403)});assert.equal(restricted.inputs.length,0);assert.equal(restricted.discoveryReports[0].status,'access-blocked')})

test('direct candidate input remains backwards compatible',async()=>{const r=await crawlCandidates([{id:'direct',url:'https://fixture.test/about'}],{fetch,delayMs:0,maxDepth:0});assert.equal(r.discoveryReports.length,0);assert.equal(r.candidates[0].candidateId,'direct')})
