import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { crawlCandidates, discoverCandidateInputs, extractCandidateName, extractContacts, identifySource } from '../crawler.mjs'

const root=new URL('./fixtures/',import.meta.url)
const files={'fixture.test/':'index.html','fixture.test/about':'about.html','fixture.test/contact':'contact.html','portfolio.test/contact':'contact.html'}
function response(body,status=200,type='text/html'){return new Response(body,{status,headers:{'content-type':type}})}
const fetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response(u.hostname==='fixture.test'?'User-agent: *\nDisallow: /private\n':'User-agent: *\n');if(u.hostname==='github.com')return response('<a href="https://portfolio.test/contact">Portfolio website</a>');const f=files[`${u.hostname}${u.pathname}`];return f?response(await readFile(new URL(f,root),'utf8')):response('',404)}

test('deep traversal crosses profile to portfolio, extracts contacts and preserves provenance',async()=>{const r=await crawlCandidates([{id:'fixture',url:'https://fixture.test/'}],{fetch,delayMs:0,maxDepth:3,maxPages:12});const c=r.candidates[0];assert.ok(c);assert.equal(c.contacts.filter(x=>x.type==='email').length,1);assert.ok(c.contacts.some(x=>x.normalized==='+998901234567'));assert.ok(c.contacts.some(x=>x.type==='telegram'));assert.ok(c.contacts.some(x=>x.normalized==='linkedin:/in/fixture-dev'));assert.ok(!c.crawledPages.includes('https://fixture.test/private'));const linked=c.contacts.find(x=>x.normalized==='linkedin:/in/fixture-dev');assert.deepEqual(linked.discoveryChain,['https://fixture.test/','https://fixture.test/about','https://fixture.test/contact']);assert.ok(c.crawledPages.includes('https://portfolio.test/contact'))})

test('contact extraction handles mailto, tel and WhatsApp deterministically',()=>{const c=extractContacts('<a href="mailto:Dev@Example.uz?subject=Hi">mail</a><a href="tel:+998 90 111 22 33">call</a><a href="https://wa.me/998901112233">wa</a>','https://x.test/');assert.ok(c.some(x=>x.normalized==='dev@example.uz'));assert.equal(c.filter(x=>x.type==='phone'&&x.normalized.includes('998901112233')).length,2)})

test('deduplicates contacts and excludes candidates with no public contact',async()=>{const r=await crawlCandidates([{id:'none',url:'https://empty.test/'},{id:'fixture',url:'https://fixture.test/'}],{fetch:async(url,...args)=>new URL(url).hostname==='empty.test'?(new URL(url).pathname==='/robots.txt'?response(''):response('<p>Hello</p>')):fetch(url,...args),delayMs:0,maxDepth:2});assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].candidateId,'fixture');assert.equal(new Set(r.candidates[0].contacts.map(x=>`${x.type}:${x.normalized}`)).size,r.candidates[0].contacts.length);assert.equal(r.sourceReports.find(x=>x.candidateId==='none').status,'no-public-contact')})

test('source adapters identify priority sources and report restrictions',async()=>{assert.equal(identifySource('https://hh.uz/resume/1').id,'hh-uz');assert.equal(identifySource('https://olx.uz/d/obyavlenie/x').id,'olx-uz');assert.equal(identifySource('https://github.com/u').id,'github');const calls=[];const blocked=async url=>{calls.push(url);return new URL(url).pathname==='/robots.txt'?response('User-agent: *\n'):response('Access denied',403)};const r=await crawlCandidates([{id:'gh',url:'https://github.com/u'},{id:'hh',url:'https://hh.uz/resume/1'}],{fetch:blocked,delayMs:0});assert.ok(calls.findIndex(x=>x.includes('hh.uz/resume'))<calls.findIndex(x=>x.includes('github.com/u')));assert.equal(r.sourceReports.find(x=>x.candidateId==='hh').status,'access-blocked')})

test('robots exclusions are explicit rather than silently omitted',async()=>{const r=await crawlCandidates([{id:'private',url:'https://fixture.test/private'}],{fetch,delayMs:0});assert.equal(r.candidates.length,0);assert.equal(r.sourceReports[0].status,'robots-disallowed');assert.equal(r.sourceReports[0].failures[0].reason,'robots-disallowed')})

test('listing adapter discovers candidates across bounded pagination and starts provenance at listing',async()=>{const listingFetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('User-agent: *\n');if(u.pathname==='/search/resume'&&!u.search)return response('<a href="/resume/alice">Alice</a><a rel="next" href="?page=2">Next</a>');if(u.searchParams.get('page')==='2')return response('<a href="/resume/alice">duplicate</a><a href="/resume/bob">Bob</a><a rel="next" href="?page=3">Next</a>');if(u.searchParams.get('page')==='3')return response('<a href="/resume/ignored">Ignored</a>');if(u.pathname==='/resume/alice')return response('<p>Email alice@example.uz</p>');if(u.pathname==='/resume/bob')return response('<a href="https://t.me/bob_dev">Telegram</a>');return response('',404)};const r=await crawlCandidates([{id:'hh-list',type:'source',url:'https://hh.uz/search/resume'}],{fetch:listingFetch,delayMs:0,maxListingPages:2,maxDepth:0});assert.equal(r.discoveryReports[0].candidateCount,2);assert.equal(r.candidates.length,2);assert.deepEqual(r.candidates[0].contacts[0].discoveryChain.slice(0,2),['https://hh.uz/search/resume','https://hh.uz/resume/alice']);assert.ok(!r.candidates.some(x=>x.inputUrl.includes('ignored')))})

test('source adapters apply candidate-link rules without copying any source name to candidates',async()=>{const cases=[['OLX — Работа','https://olx.uz/rabota/','https://olx.uz/d/obyavlenie/frontend-ID1.html'],['IT Market — специалисты','https://it-market.uz/specialists','https://it-market.uz/specialist/42'],['Ustoz Shogird','https://t.me/s/resumes','https://t.me/s/resumes/123'],['GitHub — разработчики Узбекистана','https://github.com/search?q=uzbekistan&type=users','https://github.com/alice-dev'],['Developer School','https://school.test/alumni','https://school.test/profile/alice']];for(const [sourceName,listing,candidate] of cases){const d=await discoverCandidateInputs([{id:'s',type:'source',name:sourceName,url:listing}],{delayMs:0,maxListingPages:1,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response(`<a href="${candidate}">Candidate profile</a>`)});assert.equal(d.inputs[0]?.url,candidate,listing);assert.equal(d.inputs[0]?.name,undefined,listing);assert.equal(d.inputs[0]?._listingName,undefined,listing);assert.equal(d.discoveryReports[0].status,'candidates-discovered')}})

test('extracts a real candidate name from common profile markup and rejects generic source titles',()=>{assert.equal(extractCandidateName('<script type="application/ld+json">{"@type":"Person","name":"Alice Karimova"}</script>'),'Alice Karimova');assert.equal(extractCandidateName('<meta property="og:title" content="Bob Rakhimov — GitHub">'),'Bob Rakhimov');assert.equal(extractCandidateName('<h1>Candidate profile</h1><title>Ustoz Shogird</title>'),null)})

test('Telegram listing follows before pagination and expands beyond one page',async()=>{const listingFetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');if(u.searchParams.get('before')==='100')return response('<a href="/s/resumes/80">older candidate</a>');return response('<a href="/s/resumes/100">latest candidate</a><a class="tme_messages_more" href="/s/resumes?before=100">older posts</a>')};const d=await discoverCandidateInputs([{id:'tg-list',type:'source',url:'https://t.me/s/resumes'}],{fetch:listingFetch,delayMs:0,maxListingPages:2,maxCandidates:100});assert.equal(d.discoveryReports[0].listingPages.length,2);assert.equal(d.discoveryReports[0].candidateCount,2);assert.deepEqual(d.inputs.map(x=>x.url),['https://t.me/s/resumes/100','https://t.me/s/resumes/80'])})

test('zero listing limits crawl every page until pagination ends',async()=>{const listingFetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');const before=u.searchParams.get('before');if(before==='100')return response('<a href="/s/resumes/80">second</a><a href="/s/resumes?before=80">older</a>');if(before==='80')return response('<a href="/s/resumes/60">third</a>');return response('<a href="/s/resumes/100">first</a><a href="/s/resumes?before=100">older</a>')};const d=await discoverCandidateInputs([{id:'tg-list',type:'source',url:'https://t.me/s/resumes'}],{fetch:listingFetch,delayMs:0,maxListingPages:0,maxCandidates:0});assert.equal(d.discoveryReports[0].listingPages.length,3);assert.equal(d.discoveryReports[0].candidateCount,3)})

test('Telegram candidates are isolated to one post instead of absorbing the channel page',async()=>{const html='<div class="tgme_widget_message_wrap"><div data-post="resumes/122">Xodim: Wrong Person <a href="https://t.me/wrong_user">wrong</a></div></div><div class="tgme_widget_message_wrap"><div data-post="resumes/123">Xodim: Alice Karimova Yosh: 25 <a href="https://t.me/alice_dev">contact</a><a href="https://t.me/resumes">channel</a></div></div><div class="tgme_widget_message_wrap"><div data-post="resumes/124">Xodim: Other Person <a href="https://t.me/other_user">other</a></div></div>';const r=await crawlCandidates([{id:'tg',url:'https://t.me/s/resumes/123'}],{delayMs:0,maxDepth:3,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response(html)});assert.equal(r.candidates[0]?.name,'Alice Karimova');assert.deepEqual(r.candidates[0]?.contacts.map(x=>x.normalized),['@alice_dev']);assert.equal(r.candidates[0]?.crawledPages.length,1)})

test('all listing adapters prefer each profile name and never reuse the listing title',async()=>{const cases=[['https://olx.uz/rabota/','https://olx.uz/d/obyavlenie/frontend-ID1.html'],['https://it-market.uz/specialists','https://it-market.uz/specialist/42'],['https://t.me/s/resumes','https://t.me/s/resumes/123'],['https://github.com/search?q=uzbekistan&type=users','https://github.com/alice-dev'],['https://school.test/alumni','https://school.test/profile/alice']];for(const [listing,candidate] of cases){const profileName=`Person ${new URL(candidate).hostname.replace(/\W/g,'')}`;const r=await crawlCandidates([{id:'s',type:'source',name:'Shared source title',url:listing}],{delayMs:0,maxListingPages:1,maxDepth:0,fetch:async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');if(url===listing)return response(`<a href="${candidate}">Candidate profile</a>`);if(url===candidate)return response(`<h1>${profileName}</h1><a href="mailto:person@example.uz">Email</a>`);return response('',404)}});assert.equal(r.candidates[0]?.name,profileName,listing);assert.notEqual(r.candidates[0]?.name,'Shared source title',listing)}})

test('unsupported and restricted listings are reported without fabricated candidates',async()=>{const unsupported=await discoverCandidateInputs([{id:'tp',type:'source',url:'https://talentpark.uz/search'},{id:'linkedin',type:'restricted',name:'LinkedIn',url:'https://linkedin.com/',reason:'login-required'},{id:'school',type:'unsupported',name:'School',url:'https://school.test/',reason:'no-adapter'}]);assert.equal(unsupported.inputs.length,0);assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='tp').status,'unsupported-source');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='linkedin').status,'restricted-source');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='linkedin').reason,'login-required');assert.equal(unsupported.discoveryReports.find(x=>x.sourceId==='school').status,'unsupported-source');const restricted=await discoverCandidateInputs([{id:'gh',type:'source',url:'https://github.com/search?q=x&type=users'}],{delayMs:0,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response('blocked',403)});assert.equal(restricted.inputs.length,0);assert.equal(restricted.discoveryReports[0].status,'access-blocked')})

test('filtered Telegram sources retain the query while paging and exclude vacancy posts',async()=>{const listingFetch=async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');if(u.pathname==='/s/jobs'&&u.searchParams.get('before')==='20'){assert.equal(u.searchParams.get('q'),'Узбекистан');return response('<a href="/s/jobs/10">older</a>')}if(u.pathname==='/s/jobs'&&u.searchParams.has('q'))return response('<a href="/s/jobs/20">latest</a><a href="/s/jobs?before=20">older page</a>');if(u.pathname==='/s/jobs/20')return response('<div class="tgme_widget_message_wrap"><div data-post="jobs/20">#резюме Ищу работу <a href="https://t.me/candidate_dev">contact</a></div></div>');if(u.pathname==='/s/jobs/10')return response('<div class="tgme_widget_message_wrap"><div data-post="jobs/10">Вакансия Node.js <a href="https://t.me/recruiter_user">contact</a></div></div>');return response('',404)};const r=await crawlCandidates([{id:'filtered',type:'source',url:'https://t.me/s/jobs?q=%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD',requireResumePost:true}],{fetch:listingFetch,delayMs:0,maxListingPages:0,maxCandidates:0,maxDepth:0});assert.equal(r.discoveryReports[0].listingPages.length,2);assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].contacts[0].normalized,'@candidate_dev');assert.equal(r.sourceReports.find(x=>x.candidateId==='filtered:2').failures[0].reason,'not-candidate-resume')})

test('direct candidate input remains backwards compatible',async()=>{const r=await crawlCandidates([{id:'direct',url:'https://fixture.test/about'}],{fetch,delayMs:0,maxDepth:0});assert.equal(r.discoveryReports.length,0);assert.equal(r.candidates[0].candidateId,'direct')})
