import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import {enrichCandidatePhotos,runPhotoEnrichment} from '../photo-enrichment.mjs'

function response(body,status=200,type='text/html'){return new Response(body,{status,headers:{'content-type':type}})}
const input={schemaVersion:4,candidates:[{candidateId:'a',inputUrl:'https://a.test/profile',contacts:[{sourceUrl:'https://a.test/contact'}]},{candidateId:'b',inputUrl:'https://t.me/member_name',contacts:[{sourceUrl:'https://b.test/profile'}]}]}

test('enrichment visits only existing candidate page URLs and skips Telegram member pages',async()=>{const calls=[];const result=await enrichCandidatePhotos(input,{delayMs:0,fetch:async url=>{calls.push(url);const u=new URL(url);if(u.pathname==='/robots.txt')return response('User-agent: *\n');if(u.hostname==='a.test'&&u.pathname==='/profile')return response('<meta property="og:image" content="/alice.jpg">');if(u.hostname==='b.test')return response('<img class="profile-avatar" src="/bob.jpg">');return response('',404)}});assert.equal(result.output.schemaVersion,5);assert.equal(result.output.candidates[0].photo.url,'https://a.test/alice.jpg');assert.equal(result.output.candidates[1].photo.url,'https://b.test/bob.jpg');assert.ok(!calls.includes('https://a.test/contact'));assert.ok(!calls.some(url=>url.includes('t.me/member_name')));assert.ok(calls.every(url=>url.includes('a.test')||url.includes('b.test')))})

test('checkpoint resume never refetches completed candidates',async()=>{let checkpoint,calls=[];await assert.rejects(()=>enrichCandidatePhotos(input,{delayMs:0,fetch:async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');calls.push(url);return response('<meta property="og:image" content="/photo.jpg">')},onCheckpoint:async state=>{checkpoint=structuredClone(state);throw new Error('stop')}}),/stop/);assert.deepEqual(checkpoint.completedIds,['a']);calls=[];const resumed=await enrichCandidatePhotos(input,{delayMs:0,resumeState:checkpoint,fetch:async url=>{const u=new URL(url);if(u.pathname==='/robots.txt')return response('');calls.push(url);return response('<meta property="og:image" content="/photo.jpg">')}});assert.equal(calls.length,1);assert.deepEqual(resumed.output.candidates.map(x=>x.photo.url),['https://a.test/photo.jpg','https://b.test/photo.jpg'])})

test('runner writes resumable checkpoint and atomically replaces output',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'photo-enrich-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const source=path.join(dir,'crawler.json'),checkpoint=path.join(dir,'photos.checkpoint.json');await fs.writeFile(source,JSON.stringify({candidates:[{candidateId:'a',inputUrl:'https://a.test/profile',contacts:[]}]}));await runPhotoEnrichment({inputFile:source,checkpointFile:checkpoint,delayMs:0,fetcher:async url=>new URL(url).pathname==='/robots.txt'?response(''):response('<meta name="twitter:image" content="/a.jpg">')});const output=JSON.parse(await fs.readFile(source,'utf8')),state=JSON.parse(await fs.readFile(checkpoint,'utf8'));assert.equal(output.candidates[0].photo.method,'twitter:image');assert.equal(state.completed,true);assert.equal(state.completedIds.length,1);assert.deepEqual((await fs.readdir(dir)).sort(),['crawler.json','photos.checkpoint.json'])})

test('restricted pages and mismatched checkpoints are rejected safely',async()=>{const restricted=await enrichCandidatePhotos({candidates:[{candidateId:'x',inputUrl:'https://x.test/p',contacts:[]}]},{delayMs:0,fetch:async url=>new URL(url).pathname==='/robots.txt'?response(''):response('This account is private <meta property="og:image" content="/secret.jpg">')});assert.equal(restricted.output.candidates[0].photo,undefined);await assert.rejects(()=>enrichCandidatePhotos(input,{resumeState:{inputFingerprint:'wrong'}}),/does not match/)})
