import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'
import {Button,Input} from '@cloudplus/ui'
import {ArrowLeft,Bell,Check,ExternalLink,LogOut,MapPin,Pencil,RefreshCw,Search,Settings,SlidersHorizontal,Trash2,X} from 'lucide-react'
import {BrandLogo} from './BrandLogo'
import {api} from './api'
import './developer-search.css'
import './product-completeness.css'

type Candidate={id:number;name:string;headline?:string;location?:string;experienceYears?:number;skills:string[];contacts:{type?:string;value?:string;sourceUrl?:string}[];sourceUrl?:string;photo?:{url:string;sourceUrl:string;method:string}|null;data:Record<string,unknown>}
type Criterion={id:number;name:string;query:string;filters:{location?:string;skills?:string[];minExperienceYears?:number};enabled:boolean;intervalMinutes:number;lastRunAt?:number}
type Telegram={configured:boolean;mode:string;status:string;lastConnectedAt?:number;lastError?:string}
type Match={id:number;criterionId:number;matchedAt:number;candidate:Candidate}
type Run={id:number;criterion_id:number;started_at:number;finished_at?:number;status:string;candidates_scanned?:number;matches_found?:number;error?:string}
type Page='search'|'tracking'|'settings'|'candidate'

const prefix=import.meta.env.BASE_URL.replace(/\/$/,'')
function pathFor(page:Page,id?:number){const tail=page==='candidate'?`/candidates/${id}`:`/${page}`;return `${prefix}${tail}`||tail}
function routeFromPath():{page:Page;candidateId?:number}{let p=location.pathname;if(prefix&&p.startsWith(prefix))p=p.slice(prefix.length);const match=p.match(/^\/candidates\/(\d+)/);if(match)return{page:'candidate',candidateId:Number(match[1])};if(p.startsWith('/tracking'))return{page:'tracking'};if(p.startsWith('/settings'))return{page:'settings'};return{page:'search'}}

export function ProductApp({user}:{user:{telegramUserId:string;displayName:string|null}}){
 const initial=routeFromPath(),[page,setPage]=useState<Page>(initial.page),[candidateId,setCandidateId]=useState<number|undefined>(initial.candidateId),[candidates,setCandidates]=useState<Candidate[]>([]),[criteria,setCriteria]=useState<Criterion[]>([]),[matches,setMatches]=useState<Match[]>([]),[runs,setRuns]=useState<Run[]>([]),[telegram,setTelegram]=useState<Telegram|null>(null),[query,setQuery]=useState(''),[locationFilter,setLocationFilter]=useState(''),[skillFilter,setSkillFilter]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<Criterion|null>(null)
 const navigate=useCallback((next:Page,id?:number,replace=false)=>{const path=pathFor(next,id);history[replace?'replaceState':'pushState']({},'',path);setPage(next);setCandidateId(id)},[])
 useEffect(()=>{const onPop=()=>{const r=routeFromPath();setPage(r.page);setCandidateId(r.candidateId)};addEventListener('popstate',onPop);if(location.pathname==='/'||location.pathname===`${prefix}/`)navigate('search',undefined,true);return()=>removeEventListener('popstate',onPop)},[navigate])
 const load=useCallback(async()=>{setError('');setLoading(true);try{const [c,cr,m,r,t]=await Promise.all([api<{candidates:Candidate[]}>('/api/candidates?limit=200'),api<{criteria:Criterion[]}>('/api/criteria'),api<{matches:Match[]}>('/api/monitoring/matches'),api<{runs:Run[]}>('/api/monitoring/runs'),api<{telegram:Telegram}>('/api/telegram/status')]);setCandidates(c.candidates);setCriteria(cr.criteria);setMatches(m.matches);setRuns(r.runs);setTelegram(t.telegram)}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const locations=useMemo(()=>[...new Set(candidates.map(c=>c.location).filter(Boolean) as string[])].sort(),[candidates]),skills=useMemo(()=>[...new Set(candidates.flatMap(c=>c.skills||[]))].sort(),[candidates]),visible=candidates.filter(c=>[c.name,c.headline,c.location,...(c.skills||[])].join(' ').toLowerCase().includes(query.toLowerCase())&&(!locationFilter||c.location===locationFilter)&&(!skillFilter||c.skills.includes(skillFilter))),selected=candidates.find(c=>c.id===candidateId)
 const saveCriterion=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),input={name:String(f.get('name')),query:String(f.get('query')||''),filters:{location:String(f.get('location')||'')||undefined,skills:String(f.get('skill')||'')?[String(f.get('skill'))]:[],minExperienceYears:String(f.get('experience')||'')?Number(f.get('experience')):undefined},enabled:editing?.enabled??true,intervalMinutes:Number(f.get('interval')||60)};setBusy(true);setError('');try{await api(editing?`/api/criteria/${editing.id}`:'/api/criteria',{method:editing?'PATCH':'POST',body:JSON.stringify(input)});setEditing(null);form.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить')}finally{setBusy(false)}}
 const patch=async(id:number,input:object)=>{try{await api(`/api/criteria/${id}`,{method:'PATCH',body:JSON.stringify(input)});await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 const remove=async(id:number)=>{try{await api(`/api/criteria/${id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}
 const run=async(id:number)=>{setBusy(true);try{await api('/api/monitoring/run',{method:'POST',body:JSON.stringify({criterionId:id})});await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка запуска')}finally{setBusy(false)}}
 const reconnect=async()=>{setBusy(true);try{await api('/api/telegram/reconnect',{method:'POST',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Не удалось переподключить')}finally{setBusy(false)}}
 const logout=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});location.reload()}
 const nav=(next:Page,label:string,icon:React.ReactNode)=><button className={page===next?'active':''} onClick={()=>navigate(next)}>{icon}{label}</button>
 return <div className="live-app"><aside className="live-nav"><BrandLogo/><nav>{nav('search','Поиск',<Search/>)}{nav('tracking','Отслеживание',<Bell/>)}{nav('settings','Настройки',<Settings/>)}</nav><button onClick={logout}><LogOut/>Выйти</button></aside><main className="live-main">{error&&<div className="error-banner">{error}<button aria-label="Закрыть" onClick={()=>setError('')}><X/></button></div>}{loading&&<p className="loading-state">Загрузка данных…</p>}
 {page==='search'&&<><header className="live-header"><div><h1>Поиск разработчиков</h1><p>Только кандидаты с подтвержденными публичными контактами</p></div><span>{visible.length} кандидатов</span></header><div className="live-search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Имя, роль, навык или город"/></div><div className="live-filters"><SlidersHorizontal/><select value={locationFilter} onChange={e=>setLocationFilter(e.target.value)}><option value="">Все города</option>{locations.map(x=><option key={x}>{x}</option>)}</select><select value={skillFilter} onChange={e=>setSkillFilter(e.target.value)}><option value="">Все навыки</option>{skills.map(x=><option key={x}>{x}</option>)}</select>{(locationFilter||skillFilter)&&<button onClick={()=>{setLocationFilter('');setSkillFilter('')}}>Сбросить</button>}</div><section className="live-grid">{visible.map(c=><article className="live-candidate clickable" key={c.id} tabIndex={0} onClick={()=>navigate('candidate',c.id)} onKeyDown={e=>e.key==='Enter'&&navigate('candidate',c.id)}><CandidateAvatar candidate={c}/><div><h2>{c.name}</h2><p>{c.headline||'Специализация не указана'}</p>{c.location&&<span><MapPin/>{c.location}</span>}</div><div className="live-skills">{c.skills.map(s=><b key={s}>{s}</b>)}</div><div className="live-contacts">{c.contacts.slice(0,2).map((x,i)=><span key={i}>{x.type}: {x.value}</span>)}</div></article>)}{!loading&&!visible.length&&<Empty title="Кандидатов пока нет"/>}</section></>}
 {page==='candidate'&&<CandidateProfile candidate={selected} onBack={()=>navigate('search')}/>}
 {page==='tracking'&&<><header className="live-header"><div><h1>Отслеживание</h1><p>Критерии хранятся на сервере, совпадения не дублируются</p></div></header><form className="tracking-form extended" onSubmit={saveCriterion} key={editing?.id||'new'}><Input name="name" required defaultValue={editing?.name} placeholder="Название"/><Input name="query" defaultValue={editing?.query} placeholder="Роль или слова"/><select name="location" defaultValue={editing?.filters.location||''}><option value="">Любой город</option>{locations.map(x=><option key={x}>{x}</option>)}</select><select name="skill" defaultValue={editing?.filters.skills?.[0]||''}><option value="">Любой навык</option>{skills.map(x=><option key={x}>{x}</option>)}</select><Input name="experience" type="number" min="0" defaultValue={editing?.filters.minExperienceYears} placeholder="Опыт от"/><Input name="interval" type="number" min="1" max="10080" defaultValue={editing?.intervalMinutes||60} placeholder="Интервал, мин"/><Button disabled={busy}>{editing?'Обновить':'Сохранить'}</Button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Отмена</button>}</form><div className="tracking-layout"><section>{criteria.map(c=><article className="criterion-card" key={c.id}><div><h3>{c.name}</h3><p>{c.query||'Без запроса'} · {c.intervalMinutes} мин. · опыт от {c.filters.minExperienceYears??0}</p></div><label><input type="checkbox" checked={c.enabled} onChange={e=>void patch(c.id,{enabled:e.target.checked})}/> Отслеживать</label><button onClick={()=>setEditing(c)} aria-label="Изменить"><Pencil/></button><button onClick={()=>void run(c.id)} disabled={busy} aria-label="Проверить"><RefreshCw/></button><button onClick={()=>void remove(c.id)} aria-label="Удалить"><Trash2/></button></article>)}{!criteria.length&&<Empty title="Критериев пока нет"/>}</section><section className="monitor-history"><div className="match-history"><h2>Запуски</h2>{runs.map(r=><article key={r.id} className={`run-${r.status}`}><div><b>{r.status}</b><span>{new Date(r.started_at).toLocaleString('ru')} · просмотрено {r.candidates_scanned??0} · найдено {r.matches_found??0}</span>{r.error&&<small>{r.error}</small>}</div></article>)}{!runs.length&&<p>Запусков пока нет.</p>}</div><div className="match-history"><h2>Совпадения</h2>{matches.map(m=><article key={m.id}><Check/><div><b>{m.candidate.name}</b><span>{new Date(m.matchedAt).toLocaleString('ru')}</span></div></article>)}{!matches.length&&<p>Новых совпадений пока нет.</p>}</div></section></div></>}
 {page==='settings'&&<><header className="live-header"><div><h1>Настройки</h1><p>Профиль и подключение Telegram</p></div></header><section className="settings-live"><div className="content-card"><h2>Профиль</h2><label>Telegram ID<Input value={user.telegramUserId} readOnly/></label><label>Имя<Input value={user.displayName||'Не указано'} readOnly/></label></div><div className="content-card"><h2>Telegram-бот</h2><div className={`connection-status ${telegram?.status==='connected'?'ok':''}`}><span/><div><b>{telegram?.status==='connected'?'Подключен':'Не подключен'}</b><small>{telegram?.configured?`Режим: ${telegram.mode}`:'Бот не настроен на сервере'}</small>{telegram?.lastError&&<small>{telegram.lastError}</small>}</div></div><Button onClick={reconnect} disabled={busy}><RefreshCw/>Безопасно переподключить</Button><p>Токен хранится только на сервере и никогда не передается в браузер.</p></div></section></>}</main></div>
}
function CandidateAvatar({candidate}:{candidate:Candidate}){return <div className="live-avatar">{candidate.photo&&<img src={candidate.photo.url} alt="" loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true}}/>}<span>{candidate.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')}</span></div>}
function CandidateProfile({candidate,onBack}:{candidate?:Candidate;onBack:()=>void}){if(!candidate)return <Empty title="Кандидат не найден" action={<Button onClick={onBack}>Вернуться к поиску</Button>}/>;return <section className="candidate-detail"><button className="back-link" onClick={onBack}><ArrowLeft/>К поиску</button><div className="profile-hero"><CandidateAvatar candidate={candidate}/><div><h1>{candidate.name}</h1><p>{candidate.headline||'Специализация не указана'}</p>{candidate.location&&<span><MapPin/>{candidate.location}</span>}</div></div><div className="profile-grid"><div className="content-card"><h2>Профиль</h2>{candidate.experienceYears!=null&&<p>Опыт: {candidate.experienceYears} лет</p>}<div className="live-skills">{candidate.skills.map(s=><b key={s}>{s}</b>)}</div></div><div className="content-card"><h2>Публичные контакты</h2>{candidate.contacts.map((x,i)=><p key={i}><a href={x.sourceUrl||candidate.sourceUrl} target="_blank" rel="noreferrer">{x.type}: {x.value} <ExternalLink/></a></p>)}{candidate.sourceUrl&&<p><a href={candidate.sourceUrl} target="_blank" rel="noreferrer">Открыть профиль-источник</a></p>}{candidate.photo&&<p className="photo-credit">Фото: <a href={candidate.photo.sourceUrl} target="_blank" rel="noreferrer">публичный источник</a> · {candidate.photo.method}</p>}</div></div></section>}
function Empty({title,action}:{title:string;action?:React.ReactNode}){return <div className="product-empty"><Search/><h3>{title}</h3>{action}</div>}
